### ISSUE TITLE
Add Create Goal Page

### ISSUE THREAD

**Issue by amanxnanda** [pratyushmp/Batua#26] opened 2021-03-15 14:54 UTC
Once Fix #7 gets resolved we can start working on creating a goal page

**Comment by D-Ajay-Kumar** [comment] 2021-03-15 15:27
I can do it.

**Comment by amanxnanda** [comment] 2021-03-15 16:44
@D-Ajay-Kumar bro you've been doing a lot, please let others learn open source as well.

**Comment by infiniteoverflow** [comment] 2021-03-15 17:03
@amanxnanda Kindly don't criticize any participants for showing their interest in working on any issue. And in open source there is nothing like "Doing too much" , if you are interested then you can work on any issue.

@D-Ajay-Kumar Please note if any participants create an issue and is interested in working on that , it will be assigned to them after the PA or mentors review the relevance of the issue.

And guys this OpenSource program is 3-months long, we will have tons and tons of issues coming up !! So don't worry.

**Comment by amanxnanda** [comment] 2021-03-15 17:07
@infiniteoverflow @D-Ajay-Kumar I apologise, but I saw a lot student not able to get good first issues where they can atleast start.
Again I'm sincerely sorry.

**Comment by D-Ajay-Kumar** [comment] 2021-03-15 17:07
Oh, I thought this was opened by one of the maintainers so asked if I could do it. But if the author of the issue is a participant himself/herself then please go ahead and solve it.

**Comment by D-Ajay-Kumar** [comment] 2021-03-15 17:09
Btw I'm a beginner too :)

**Comment by infiniteoverflow** [comment] 2021-03-15 17:12
@amanxnanda Dont be sorry, it happens for anyone. Even i had been like this when i started with GSSOC 19.

But dont worry @pratyushmp is planning for coming up with more good first issues for anyone to get started with.

And one more thing i would suggest you guys learn as much as you can , and try working on harder issues. This will help you gain more experience.
You don't wanna get stuck solving Level2 issues the entire GSSOC period right.

**Comment by infiniteoverflow** [comment] 2021-03-15 17:15
@pratyushmp Will update soon on his plan of solving this issue. So just wait for some time.

**Comment by pratyushmp** [comment] 2021-03-15 17:22
Rightly said @infiniteoverflow . @amanxnanda and @D-Ajay-Kumar really appreciate your participation, there will be a lot of issues that you guys can work on. And there will be some beginner friendly issues too. Even if you don't find issues that are of your level keep going through the code contributed by other participants and keep learning. Because at the end we are all here for learning :)

**Comment by pratyushmp** [comment] 2021-03-15 17:29
The issue will be assigned to @amanxnanda since you have created the issue. But you can start working on it only after issue #7 is reviewed and merged.

**Comment by amanxnanda** [comment] 2021-03-15 17:30
Thanks for assigning

**Comment by pratyushmp** [comment] 2021-03-28 04:59
@amanxnanda Status of goal page? It's been 12 since the issue has been assigned to you.

**Comment by pratyushmp** [comment] 2021-03-28 17:39
@D-Ajay-Kumar Would you like to take up this issue?

**Comment by SapinderSingh** [comment] 2021-03-28 23:20
@pratyushmp I would like to work on this issue.

**Comment by pratyushmp** [comment] 2021-03-29 05:05
@D-Ajay-Kumar had earlier asked me to assign this issue to him, if he doesn't respond by today or tomorrow the issue will be assigned to you @SapinderSingh !

**Comment by SapinderSingh** [comment] 2021-03-29 05:09
@pratyushmp No Problem :)

**Comment by D-Ajay-Kumar** [comment] 2021-03-29 15:59
Is there a screenshot of the screen to be made?

**Comment by pratyushmp** [comment] 2021-03-29 16:01
@D-Ajay-Kumar It is the 4th screen in the UI design given in ```Readme.md```

**Comment by pratyushmp** [comment] 2021-04-02 05:50
@D-Ajay-Kumar Status?

**Comment by pratyushmp** [comment] 2021-04-06 11:23
@SapinderSingh You can start working on this issue

**Closed** 2021-04-15 10:18 UTC
Labels: GSSOC21, Level2
