### ISSUE TITLE
Add Spinner in Login_Screen

### ISSUE THREAD

**Issue by rakshitkamboj** [pratyushmp/Batua#58] opened 2021-03-25 13:30 UTC
After clicking on loginScreen it takes some time to get response from firebase in the meantime the app didn't perform any activity and it looks stucked. So, To show the progress to the user I would like to add a spinner that will showup untill app screen navigate to next screen.
I will be using modal_progress_hud package for that.

**Comment by pratyushmp** [comment] 2021-03-25 14:38
Sure @rakshitkamboj . The issue is assigned to you

**Closed** 2021-03-27 13:35 UTC
Labels: GSSOC21, Level2
